### ISSUE TITLE
path.getBindingIdentifierPaths

### ISSUE THREAD

**Issue by mauricionr** [austinkelleher/lasso-prepack#1]
i added lasso-prepack to array of plugins and got this error

TypeError: path.getBindingIdentifierPaths is not a function
    at Object.AssignmentExpressionUpdateExpression

**Comment by austinkelleher** [comment]
Hm that's odd. What version of Node and what OS are you using?

**Comment by austinkelleher** [comment]
Also could you provide a stack trace if there is one? Thanks.

**Comment by mauricionr** [comment]
@austinkelleher 

```LOGS
user@user:~/workspace/project (master)$ node -v
v7.6.0
user@user:~/workspace/project (master)$ git --version
git version 2.7.4
user@user:~/workspace/project (master)$ yarn --version
0.23.2
user@user:~/workspace/project (master)$ lsb
lsblk        lsb_release  
user@user:~/workspace/project (master)$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

```javascript
require('lasso').configure({
  plugins: [
    'lasso-marko', // Allow Marko templates to be compiled and transported to the browser
    'lasso-prepack'
  ],

```

```LOGS

TypeError: path.getBindingIdentifierPaths is not a function
    at Object.AssignmentExpressionUpdateExpression (/home/user/workspace/project/node_modules/prepack/lib/serializer/visitors.js:77:20)
    at NodePath._call (/home/user/workspace/project/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/home/user/workspace/project/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/home/user/workspace/project/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/home/user/workspace/project/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/home/user/workspace/project/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/home/user/workspace/project/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/home/user/workspace/project/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/home/user/workspace/project/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/home/user/workspace/project/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/home/user/workspace/project/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/home/user/workspace/project/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/home/user/workspace/project/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/home/user/workspace/project/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/home/user/workspace/project/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/home/user/workspace/project/node_modules/babel-traverse/lib/context.js:108:19)
Error: Render error. Exception: TypeError: Cannot read property 'user' of undefined
    at render (/home/user/workspace/project/app/views/layouts/mobile/default.marko.js:72:38)
    at safeRender (/home/user/workspace/project/node_modules/marko/runtime/renderable.js:6:9)
    at Template.render (/home/user/workspace/project/node_modules/marko/runtime/renderable.js:136:20)
    at doInclude (/home/user/workspace/project/node_modules/marko/taglibs/core/include-tag.js:17:31)
    at includeTag (/home/user/workspace/project/node_modules/marko/taglibs/core/include-tag.js:30:5)
    at render (/home/user/workspace/project/app/views/pages/mobile/error/error.marko.js:23:5)
    at safeRender (/home/user/workspace/project/node_modules/marko/runtime/renderable.js:6:9)
    at Template.render (/home/user/workspace/project/node_modules/marko/runtime/renderable.js:136:20)
    at module.exports (/home/user/workspace/project/config/middlewares/renderError.js:8:12)
    at Layer.handle_error (/home/user/workspace/project/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/user/workspace/project/node_modules/express/lib/router/index.js:310:13)
    at /home/user/workspace/project/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/user/workspace/project/node_modules/express/lib/router/index.js:330:12)
    at next (/home/user/workspace/project/node_modules/express/lib/router/index.js:271:10)
    at logErrors (/home/user/workspace/project/config/middlewares/logErrors.js:12:5)
    at Layer.handle_error (/home/user/workspace/project/node_modules/express/lib/router/layer.js:71:5)
    at AsyncStream.error (/home/user/workspace/project/node_modules/marko/runtime/html/AsyncStream.js:411:13)
    at Timeout._onTimeout (/home/user/workspace/project/node_modules/marko/runtime/renderable.js:17:22)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)


```

**Comment by mauricionr** [comment]
@austinkelleher any updates? i will test it again
